version: "3"
services:
  sync:
    image: wazopbx/wait
    depends_on:
      - db
    environment:
      TARGETS: "db:5432"
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  db:
    image: postgres:11
    expose:
     - "5432"
    environment:
     - POSTGRES_USER=asterisk
     - POSTGRES_PASSWORD=proformatique
     - POSTGRES_DB=asterisk
    volumes:
      - "./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"

  purgedb:
    image: wazo-purge-db-test
    environment:
      - XIVO_TEST_DB_URL=postgresql://asterisk:proformatique@db/asterisk
    volumes:
      - "..:/usr/src/wazo-purge-db"
