# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: '/etc/wazo-purge-db/conf.d/'

pid_file: '/var/run/wazo-purge-db.pid'
log_file: '/var/log/wazo-purge-db.log'

# Database connection informations.
db_uri: 'postgresql://asterisk:proformatique@localhost/asterisk'

days_to_keep: 365
debug: False

enabled_plugins:
    purgers:
        call-log: true
        cel: true
        queue-log: true
        stat-agent: true
        stat-call-on: true
        stat-queue: true
        stat-switchboard: true
#    archives:
#        - sample
