# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/xivo-call-logd/conf.d/

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@localhost/asterisk

log_filename: /var/log/xivo-purge-db.log

days_to_keep: 365


